name: 🐛 Bug report
description: Use this format to fill a bug report.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: '# Bug report'

  - type: textarea
    id: description
    attributes:
      label: Description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Tell us how to reproduce this bug or how you found it
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Media, if necessary
      description: Screenshot, GIF, video, etc.
    validations:
      required: false
