contact_links:
  - name: Discord Community Support
    url: https://discord.gg/ktypkdpkDz
    about: You can also join our Discord server to engage with the community and get support.
blank_issues_enabled: false